services:
  mysql:
    image: mysql:8.0
    container_name: techx-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "127.0.0.1:${MYSQL_PORT}:3306"
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - techx_mysql_data:/var/lib/mysql

volumes:
  techx_mysql_data: